apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    run: msa2-svc-order
  name: msa2-svc-order
spec:
  replicas: 1
  selector:
    matchLabels:
      run: msa2-svc-order
  template:
    metadata:
      labels:
        run: msa2-svc-order
    spec:
      containers:
      - image: 192.168.100.102:5000/msasmp02/msa2-svc-order:1.0
        imagePullPolicy: Always
        name: msa2-svc-order
        ports:
        - containerPort: 9092
          protocol: TCP
      restartPolicy: Always

