kubectl delete -f ./msa2-svc-member/service.yml
kubectl delete -f ./msa2-svc-member/deployment.yml
kubectl delete -f ./msa2-svc-order/deployment.yml
kubectl delete -f ./msa2-svc-order/service.yml
kubectl delete -f ./msa2-zuul-server/deployment.yml
kubectl delete -f ./msa2-zuul-server/service.yml
kubectl delete -f ./msa2-zuul-server/ingress.yml
kubectl delete -f ./msa2-turbine-server/deployment.yml
kubectl delete -f ./msa2-turbine-server/service.yml
kubectl delete -f ./msa2-dashboard-server/deployment.yml
kubectl delete -f ./msa2-dashboard-server/service.yml
kubectl delete -f ./msa2-dashboard-server/ingress.yml
