apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-mem-quota
  namespace: msasmp01 
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 3Gi