#Eureka Standalone Server
spring:
  application:
    name: msa2-eureka-server
server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true         #HostName이 IP 에 의존하여 설정
  client:
    registerWithEureka: false       #자체 서비스를 eureka 서버에 등록 할지 여부
    fetchRegistry: false            #client 서비스가 eureka 서버로 부터 서비스 리스트 정보를 local에 caching 할지 여부
    server:
      waitTimeInMsWhenSyncEmpty: 0  #레지스트리 정보를 가져 오지 못할 경우 바로 재시도
    serviceUrl:
      defaultZone: http://msa2-eureka-server:${server.port}/eureka/
      