server:
  port: 9091

spring:
  application:
    name: msa2-svc-member
  sleuth:
    sampler:
      probability: 1.0    #얼마나 많은 비율로 zipkin에 송신하는 transaction 비율(Default 0.1(10%), 설정 1.0(100%))
  zipkin:
    base-url: http://msa2-zipkin-server:9411 #ZipKin Server      

  cloud:
    kubernetes:
#      config:
#        enabled: true
#      reload:
#        enabled: true
#        mode: polling
#        strategy: RESTART_CONTEXT
        
      discovery:
        all-namespaces: true
        #enabled: false   
      ribbon:
        mode: SERVICE
           
    stream:
      bindings:
        hystrixStreamOutput:
          destination: ddo
          binder: rabbit1
        orderMsgChannel:
          destination: act
          binder: rabbit2
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq1
                port: 5672
                username: guest
                password: guest
        rabbit2:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq2
                port: 5672
                username: guest
                password: guest  
  data:
    mongodb:
      host: mongodb-standalone-0.mongodb
      username: user
      password: password
      database: sample01
      port: 27017
    
#turbine 수집을 위한 endpoint 활성화        
management:
  endpoints:
    web:
      exposure:
        include: "*"     

springfox:
  documentation:
    swagger:
      v2:
        path: /member/api-docs        

ribbon:
  http:
    client:
      enabled: true        